version: "3.3"
service:
  mongodb:
    container_name: mongodb
    image: sohailshaik23/wanderlust_mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data
      
  backend:
    container_name: backend
    image: sohailshaikh23/wanferlust_backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.sample
    depends_on:
      - mongodb
    
    frontend:
    container_name: frontend
    image: sohailshaikh23/wanderlust_frontend:latest
    env_file:
      - ./backend/.env.sample
    ports:
      - "5173:5173"

volumes:
  data:
